apiVersion: v1
kind: Namespace
metadata:
  name: kyndryl-workshop-namespace  # Reemplaza esto con el nombre que desees para tu Namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyndryl-workshop-deployment
  namespace: kyndryl-workshop-namespace  # Especifica el Namespace personalizado aquí
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyndryl-workshop-aplicacion
  template:
    metadata:
      labels:
        app: kyndryl-workshop-aplicacion
    spec:
      containers:
        - name: kyndryl-workshop-contenedor
          image: noriegadocker/workshop-unit-test:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: kyndryl-workshop-servicio
  namespace: kyndryl-workshop-namespace  # Especifica el Namespace personalizado aquí
spec:
  type: LoadBalancer
  selector:
    app: kyndryl-workshop-aplicacion
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: port80
      #nodePort: 30007